#!/bin/sh

set -eux

ATC_PORT_8080_TCP_ADDR=$(cat /etc/hosts | head -n 1 | cut -d '	' -f 1)
ATC_PORT_8080_TCP_PORT=8080

exec atc \
  --templates /atc/templates \
  --public /atc/public \
  --postgres-data-source "postgres://postgres@$DB_PORT_5432_TCP_ADDR:$DB_PORT_5432_TCP_PORT/postgres?sslmode=disable" \
  --peer-url "http://$ATC_PORT_8080_TCP_ADDR:$ATC_PORT_8080_TCP_PORT" \
  --cli-artifacts-dir /atc \
  --development-mode
