FROM golang:1.4.2

RUN apt-get update && apt-get -y install btrfs-tools iptables ulogd zip

ADD garden-linux-release/src/ /garden/src

ENV GOPATH /garden
ENV PATH /garden/bin:$PATH

RUN go install -tags daemon github.com/cloudfoundry-incubator/garden-linux
RUN cd $GOPATH/src/github.com/cloudfoundry-incubator/garden-linux && make
CMD tar cvf - /garden | gzip -9c
